sovle the prepare_data error
when convert bin datasets to folders, it will report:
```
Traceback (most recent call last):
  File "prepare_data.py", line 12, in <module>
    load_mx_rec(rec_path)
  File "/home/user1/InsightFace_Pytorch/data/data_pipe.py", line 92, in load_mx_rec
    label = int(header.label)
TypeError: only size-1 arrays can be converted to Python scalars
```